In [4]:
import torch
print(torch.__version__)

2.2.2


In [5]:
import random

# Create a 3x3 matrix (list of lists) with random float values
matrix = [[random.random() for _ in range(3)] for _ in range(3)]
# print(matrix)

# Importance of Tensors in Neural Networks
In neural networks, tensors represent inputs, outputs, weights, and biases. For instance, an input layer of a neural network can be represented as a tensor where each element corresponds to a feature in the input data. Tensors enable efficient computation of forward and backward passes during training, making them a fundamental building block in deep learning.

In [6]:
import torch

tensor1 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
tensor2 = torch.tensor([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0], [3.0, 2.0, 1.0]])
# print(tensor1)
# Element-wise addition
result = tensor1 + tensor2
# print(result)

## TENSOR Manipulation

In [7]:
# Reshaping Tensors: Changing the shape of a tensor without changing its data.
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reshaped_tensor = tensor.view(1, 9)
# print(reshaped_tensor)

In [8]:
# Reshaping Tensors: Changing the shape of a tensor without changing its data.
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print(tensor)
# Basic slicing
sliced_tensor = tensor[:, 1]  # Select all rows in the second column
# print(sliced_tensor)

# Boolean indexing
boolean_tensor = tensor[tensor > 5]  # Select elements greater than 5
# print(boolean_tensor)

In [9]:
# Concatenation: Combining multiple tensors along a specific dimension.
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
concatenated_tensor = torch.cat((tensor1, tensor2), dim=0)  # Concatenate along rows
print(concatenated_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [10]:
# Stacking: Stacking tensors along a new dimension.
stacked_tensor = torch.stack((tensor1, tensor2), dim=1)  # Stack along columns
print(stacked_tensor)

tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


## Tensor Methods
PyTorch provides a wide range of tensor methods that are essential for building and optimizing neural networks. These methods include mathematical operations, aggregation, and transformation functions.

In [11]:
# Shape and Size:
tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(tensor.shape)  # Shape of the tensor
print(tensor.size())  # Size of the tensor

torch.Size([2, 2])
torch.Size([2, 2])


In [12]:
# Number of Dimensions:
print(tensor.ndim)  # Number of dimensions

2


In [13]:
# Data Type:
print(tensor.dtype)  # Data type of the tensor

torch.float32


In [14]:
# Unsqueeze:
unsqueezed_tensor = tensor.unsqueeze(0)  # Add an extra dimension at position 0
print(unsqueezed_tensor)

tensor([[[1., 2.],
         [3., 4.]]])


In [15]:
# Reveal:
raveled_tensor = tensor.ravel()  # Flatten the tensor
print(raveled_tensor)

tensor([1., 2., 3., 4.])


In [16]:
# Reshape:
reshaped_tensor = tensor.reshape(1, 4)  # Reshape tensor to 1x4
print(reshaped_tensor)

tensor([[1., 2., 3., 4.]])


In [17]:
# Split:
split_tensors = tensor.split(1, dim=0)  # Split tensor into chunks along dimension 0
for t in split_tensors:
    print(t)

tensor([[1., 2.]])
tensor([[3., 4.]])


In [18]:
# Mathematical Operations:
sum_tensor = tensor.sum()  # Sum of all elements
mean_tensor = tensor.mean()  # Mean of all elements
print(sum_tensor, mean_tensor)

tensor(10.) tensor(2.5000)


In [19]:
# Aggregation Functions:
max_val, max_idx = tensor.max(dim=0)  # Max values and their indices along a dimension
print(max_val, max_idx)

tensor([3., 4.]) tensor([1, 1])


In [20]:
# Transformation Functions:
transposed_tensor = tensor.t()  # Transpose of the tensor
print(transposed_tensor)

tensor([[1., 3.],
        [2., 4.]])


## Scenarios for Tensor Methods

In [21]:
# Normalization: Often, input data needs to be normalized before feeding it into a neural network. This can be done using tensor operations.
tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
normalized_tensor = (tensor - tensor.mean()) / tensor.std()
print(normalized_tensor)

tensor([[-1.1619, -0.3873],
        [ 0.3873,  1.1619]])


In [22]:
# Broadcasting: This feature allows you to perform operations on tensors of different shapes by automatically expanding their dimensions.
tensor1 = torch.tensor([1.0, 2.0, 3.0])
tensor2 = torch.tensor([[1.0], [2.0], [3.0]])
result = tensor1 + tensor2  # Broadcasting to match dimensions
print(result)

tensor([[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])
